CountryList = []
class country():
    def __init__(self, country):
        self.country = country 
        self.camount = 0
        self.cget = 0
        self.gscore = 0
        CountryList.append(self)

    def Durschnitt(self, score):
        self.gscore += score
        Durschnitt = self.gscore / self.camount
    def __str__(self):
        return  self.country

Albania = country("Albania")
Andorra = country("Andorra")
Argentinia = country("Argentinia")
Australia = country("Australia")
Austria = country("Austria")
Bangladesch = country("Bangladesch")
Belgium = country("Belgium")
Bhutan = country("Bhutan")
Brasil = country("Brasil")
Bolivia = country("Bolivia") 
Botswana = country("Botswana")
Bosnia = country("Bosnia")
Bulgaria = country("Bulgaria")
Canada = country("Canada")
Colombia = country("Colombia")
Cambodia = country("Cambodia") 
Chile = country("Chile")
Curacau = country("Curacau")
Croatia = country("Croatia")
Costa_Rica = country("Costa_Rica")
Cyprus = country("Cyprus")
Czechia = country("Czechia")    
Denmark = country("Denmark")
Domenica = country("Domenica")   
Estland	= country("Estland")
Eswatini = country("Eswatini")	
France = country("France")	
Finnland = country("Finnland")	
Germany	= country("Germany")
Ghana = country("Ghana") 	
Greenland = country("Greenland") 	
Greek = country("Greek")	
Guatamala = country("Guatamala")	
Hungary = country("Hungary")	
Hong_Kong = country("Hong_Kong")	
Indien = country("India")	
Indonesia = country("Indonesia")	
Italy = country("Italy")	
Ireland	= country("Ireland")
Island	= country("Island")
Israel = country("Israel")	
Japan  = country("Japan")	
Jordan = country("Jordan")	
Jersey = country("Jersey")
Kazakhstan = country("Kazakhstan")	
Kenia = country("Kenia") 	
Kyrgistan = country("Kyrgistan")	
Latvia = country("Latvia") 	
Lesotho = country("Lesotho")	
Libanon	= country("Libanon")
Lithuania = country("Lithuania") 	
Luxembourg = country("Luxembourg")	
Macau = country("Macau")	
Malaysia = country("Malaysia")	
Malta = country("Malta")	
Mexico = country("Mexico")	
Montenegro = country("Montenegro")	
Monaco = country("Monaco")	
Namibia	= country("Namibia")
Netherlands	= country("Netherlands")
New_Zealand = country("New_Zealand")
Nepal = country("Nepal")
Nigiria = country("Nigiria")
Norway = country("Norway")
North_Macedonia = country("North_Macedonia")
Oman = country("Oman")
Panama = country("Panama")
Paraguay = country("Paraguay")
Peru = country("Peru")
Phillipines = country("Phillipines")
Puerto_Rico = country("Puerto_Rico")
Poland = country("Poland")
Portugal = country("Portugal")
Qatar = country("Qatar")	
Russia = country("Russia")	
Ruanda = country("Ruanda")	
Romania	= country("Romania")
Sweden = country("Sweden")	
Senegal = country("Senegal")	
Serbia = country("Serbia")	
Slovakia = country("Slovakia")	
Slovenia = country("Slovenia")	
South_Africa = country("South_Africa")
South_Korea = country("South_Korea")
Spain = country("Spain")	
Sri_Lanka = country("Sri_Lanka")
Swizerland = country("Swizerland")
Taiwan = country("Taiwan")
Thailand = country("Thailand")
Tunisia = country("Tunisia")
Türkiye = country("Türkiye")
UAE = country("UAE")
Uganda = country("Uganda")
Ukraine = country("Ukraine")
United_Kingdom = country("United_Kingdom")
Uruguay = country("Uruquay")
USA = country("USA")
Vietnam = country("Vietnam")




